README.md

this was the only instance of `createAndRun` that i found in the docs. can this be updated at pypi without doing a new release somehow, since the `run` change has already been released? cc @mkulaczkowski @BartoszCki

docs(readme): change createAndStart to run

---

gradient/commands/projects.py

Without this change tests are failing because timezone info is being added to Created field in projects list table

Looks like some dependency made the datetime->str format to change.

---

gradient/api_sdk/clients/model_client.py
gradient/api_sdk/repositories/models.py
gradient/cli/models.py
gradient/commands/models.py
tests/config_files/models_upload.yaml

**Ticket:** https://paperspace.atlassian.net/browse/PS-12321
**Description of changes:**
Previously model upload in CLI was working only with file. To change it to work with file or directory argument filter was changes from `click.File()` to `click.Path(exist=True)` so now we do not open file on command start but pass string with provided path.
The issue to solve in further stage of changes be sure that relative directory structure is correct and probably try to use streaming with upload (in case if there would be one file much bigger)

Update model upload CLI command to work with file or directory

---

gradient/cli/notebooks.py

**Ticket:** https://paperspace.atlassian.net/browse/PS-12550
**Description:** Change `--id` parameter to required. That cause that if not passed then error message looks like this `Error: Missing option "--id".`

Change option `--id` to required for notebook show

---

gradient/api_sdk/s3_uploader.py
gradient/workspace.py
tests/functional/test_experiments.py
tests/unit/test_workspace.py

Reverts Paperspace/gradient-cli#183
Tests are failing for 
ERROR:   py27-pt46-ptc28: commands failed
ERROR:   py35-pt46-ptc28: commands failed
ERROR:   py36-pt46-ptc28: commands failed
ERROR:   py37-pt46-ptc28: commands failed
ERROR:   py38-pt46-ptc28: commands failed

Revert "Pass clusterhandle to experiments workspace"

---

gradient/cli/common.py
gradient/cli/experiments.py
tests/config_files/experiments_create_multi_node_ds_objs.yaml
tests/conftest.py
tests/functional/test_experiments.py

When using the --createOptionsFile, output datasets as
an array of dataset objects rather than parallel dataset
option lists.

output datasets as object array in options file PS-12630

---

gradient/commands/experiments.py

Can't verify the prod api is ready for this at the moment

Make --workspace optional again for VPC experiments

---

gradient/api_sdk/clients/__init__.py
gradient/api_sdk/clients/sdk_client.py
gradient/api_sdk/clients/secret_client.py
gradient/api_sdk/models/__init__.py
gradient/api_sdk/models/secret.py
gradient/api_sdk/repositories/__init__.py
gradient/api_sdk/repositories/secrets.py
gradient/api_sdk/serializers/__init__.py
gradient/api_sdk/serializers/secret.py
gradient/cli/__init__.py
gradient/cli/secrets.py
gradient/commands/secrets.py
setup.py
tests/example_responses.py
tests/functional/test_secrets.py

This adds secret management for teams, clusters, and projects.
Example usage
```
$ gradient secrets set team --name=aws_secret_access_key --value=test
Set team secret 'aws_secret_access_key'
$ gradient secrets list team
+-----------------------+
| Name                  |
+-----------------------+
| aws_secret_access_key |
+-----------------------+
$ gradient secrets delete team --name=aws_secret_access_key
Deleted team secret 'aws_secret_access_key'
```
*NOTE: the APIs to support secrets aren't live yet. We should wait to merge until they are available.*

Add secrets

---

.circleci/config.yml
gradient/version.py
setup.py

Add semantic-release to this repo. Pre release versions should be installed
using pip's native support for installing from a branch, e.g.
`pip install git+https://github.com/Paperspace/gradient-cli.git@chore-release-automation`

chore: release automation

---

gradient/api_sdk/clients/model_client.py
gradient/api_sdk/models/model.py
gradient/api_sdk/repositories/models.py
gradient/api_sdk/s3_uploader.py
gradient/api_sdk/serializers/model.py
gradient/cli/models.py
tests/config_files/models_upload.yaml
tests/functional/test_models.py

QA test plan (on Google SAML *prod* team):
```
pip install git+https://github.com/Paperspace/gradient-cli.git@feat-model-cluster-id
mkdir mymodel
gradient models download --id mos97714rseian9 --destinationDir mymodel
gradient models upload --modelType Tensorflow --name "test cluster model" --clusterId cljko0n9w mymodel
gradient deployments create --deploymentType TFServing --modelId <MODEL_ID> --name "test model upload" --imageUrl tensorflow/serving:2.1.0-gpu --clusterId cljko0n9w --machineType P4000 --instanceCount 1
gradient deployments start --id <DEPLOYMENT_ID>
```

feat(models): support optional clusterId param PS-15019

---

gradient/api_sdk/clients/notebook_client.py
gradient/api_sdk/repositories/notebooks.py
gradient/cli/notebooks.py
gradient/commands/notebooks.py
tests/functional/test_notebooks.py

https://linear.app/paperspace/issue/N-39/make-projectid-a-required-parameter-to-fork-in-the-cli
QA test plan:
1) try to fork a notebook without a projectId and fail 😿 
2) create a project, note id
3) try to fork a notebook with projectId and succeed 😸 
4) confirm that the notebook is in fact in that project via `notebooks details`

feat(notebooks): require projectId to fork notebook N-39

---

gradient/cli/deployments.py
gradient/cli/experiments.py
gradient/cli/jobs.py
gradient/cli/notebooks.py

Currently we're only allowing get metrics for this hard coded list of options `cpuPercentage, memoryUsage, gpuMemoryFree, gpuMemoryUsed, gpuPowerDraw, gpuTemp, gpuUtilization, gpuMemoryUtilization`. if user inputs anything other than those options, the cli will raise an error. we want to relax this validation to support custom metrics
We also want to show known metrics in the --help text
QA plan: 
1. Try getting custom metric for deployments, run command `gradient deployments metrics get --id desmvfs1gxebznb --metric iamcustom`, should return null instead of showing an error
2. Run command `gradient deployments metrics --help`, check if the `get` command help text now mentions `cpuPercentage, memoryUsage, gpuMemoryFree, gpuMemoryUsed, gpuPowerDraw, gpuTemp, gpuUtilization, …

fix(metrics): get command relax validation to allow any --metric

---

gradient/cli/workflows.py

chore(workflows): disable CLI logs 

---

.circleci/config.yml
Dockerfile
gradient/api_sdk/clients/model_client.py
gradient/api_sdk/models/model.py
gradient/api_sdk/repositories/__init__.py
gradient/api_sdk/repositories/models.py
gradient/api_sdk/repositories/workflows.py
gradient/api_sdk/serializers/model.py
gradient/cli/models.py
gradient/commands/models.py
tests/functional/test_models.py

This adds the ability to create a model with a dataset ref.
Test plan:
1. Uninstall current version of gradient-cli `pip uninstall gradient`
2. Install this version of gradient-cli: `pip install git+https://github.com/Paperspace/gradient-cli.git@roger/pla-190-make-a-model-create-container`
2. Create a dataset and two datasetVersions. Tag one of the versions with v1.
3. Create multiple models with a similar command
```
gradient models create --name roger_cli_manual_test --modelType custom --datasetRef dsr8k5qzn401lb5:v1 --projectId pradp363a
```
where projectId is the projectId, datasetRef is one of the following
- dsr8k5qzn401lb5 (no version, defaults to latest)
- dsr8k5qzn401lb5:klfoyy9 (dataset and version
- dsr8k5qzn401lb5:v1 (tag)
- dsr8k5qzn401lb5:latest

feat(models): add model create command

---

Dockerfile

Since it wasn't pinned it was installing 1.4.5 and can result in versions updating inadvertently.

fix(docker): pin dockerfile's gradient-sdk version to 1.5.0

---

.circleci/config.yml

This error was showing up in builds 
```
Directory (.) you are trying to checkout to is not empty and not a git repository
```

fix(circle): run build_and_push in a new dir

---

gradient/cli/models.py

these fields are required to download a model from the CLI :-)
straightforward PR and more of a sanity-check that these 3 actions still work in the CLI
QA: confirm that you can download 3 types of models from the CLI:
- this last upload should also work but may include the model file(s) in a nested directory structure - this is ok bc we will be retiring this method.  but confirm the rest of the download actions only download the model file(s) as expected

fix(models): require model download params pla-158

---

.gitignore
gradient/api_sdk/clients/__init__.py
gradient/api_sdk/clients/sdk_client.py
gradient/api_sdk/clients/tensorboards_client.py
gradient/commands/experiments.py
pyvenv.cfg

```python
from gradient.api_sdk.clients import sdk_client
sdk_client.DatasetsClient
```
Should show: `<class 'gradient.api_sdk.clients.dataset_client.DatasetsClient'>`

fix(sdk): expose datasets client as part of the sdk_client PLA-366

---

gradient/commands/workflows.py

QA test plan:
Run a workflow. Run `gradient workflows get --show-runs --id  ...`. The table's forth column should be the logId of the workflow run.

fix(workflows): emit the run's log id in get --show-runs

---

gradient/commands/workflows.py

fix(workflows): display log id of a started workflow PLA-374

---

gradient/api_sdk/clients/notebook_client.py
gradient/api_sdk/models/notebook.py
gradient/cli/notebooks.py

Tested against psdev, created a notebook in the UI, stopped it, ran
```bash
python3 -m gradient notebooks start \
--clusterId <cluster ID> \
--machineType psdev-worker
--notebookId <notebook ID>
```
and saw the notebook successfully restart. Verified that `--name` was no
longer a valid CLI param for the command with
```bash
python3 -m gradient notebooks start --help
```

fix(notebooks): remove --name from `gradient notebooks start` command

---

gradient/commands/datasets.py

Overview:
The command was getting a presigned url without providing file name and would get 403'd
Test plan:
1. Create a dataset version: ```gradient datasets versions create --id <dataset id>```
2. Start various ways of putting files
```
gradient datasets files put --id <dataset ref from above> --source-path file.txt
gradient datasets files put --id <dataset ref from above> --source-path workflow.yaml --target-path helloworld/
gradient datasets files put --id <dataset ref from above> --source-path workflow.yaml --target-path helloworld/yoloswag
gradient datasets files put --id <dataset ref from above> --source-path random/test/
```
putting a file, putting a folder, putting a file in a target path
3. Commit the dataset ```python gradient datasets versions commit --id <dataset ref from …
```

fix(datasets): fix datasets files put command

---

Pipfile.lock
gradient/cli/workflows.py
gradient/commands/common.py

Overview:
The workflows logs command was looking for logs for the top level run when it should iterate through the jobs for logs.
This also disables the --follow flag for now since we don't support following multiple jobs.

fix(workflows): fix workflow logs command not finding logs

---

gradient/cli/workflows.py

Results weren't returning if projectId wasn't provided. This makes the field required so there isn't confusion if not results are returned.

fix(workflows): make projectId required when listing workflows

---

gradient/api_sdk/repositories/__init__.py
gradient/api_sdk/repositories/gradient_deployments.py

This hijacks some old crufty log machinery to enable log streaming from
the new Deployments V3. This exposes two new methods, one generator and
one that just dumps a buttload of logs in your lap.
By way of example:
```
>>> from gradient import gradient_deployments
>>> import json
>>>
>>>
>>> logs = gradient_deployments.get_deployment_logs(
...     deployment_id='6753a6cc-393a-478d-bc29-9e8828a0aa2f',
...     limit=5,
...     api_key='<REDACTED>')
>>> print(json.dumps(logs, indent=4))
[
[
2,
"",
"2021-12-13T21:41:39.711Z"
],
[
3,
"  Welcome to Streamlit. Check out our demo in your browser.",
"2021-12-13T21:41:39.711Z"
],
[
4,
"",
"2021-12-13T21:41:39.711Z"
],
[
5,
"  Network URL: http://10.42.40.230:8501",
"2021-12-13T21:41:39.711Z"
],
[
6,
"  External URL: http://172.83.13.4:8501", …
```

feat(deployments): add logs to python package

---

gradient/commands/datasets.py

This attempts to fall back to a multipart upload strategy with presigned
URLs in the event that a dataset is larger than 500MB

feat(datasets): allow multipart uploads for large datasets

---

.gitignore
gradient/commands/datasets.py

After some digging, it turns out that larger files were timing out due to the default timeout of 5 seconds. Since the errors are happening inside of the worker pool, they are never reported to the user.
- Increases the default timeout to 5 minutes per 15MB file
- Better use of the `requests.Session()` context so that connection pooling is used and connections to a given host are maintained between requests. This should yield slightly better performance for parallel uploads.
- Report progress to the user more often (every chunk). There is still much room for improvement here :)
https://user-images.githubusercontent.com/98760247/174931085-fe9ccc77-c43d-4024-a26f-6bd8ffbaa195.mov

fix(datasets): increase create version request timeout

---

gradient/commands/datasets.py

PR #384 for allowing multipart uploads [introduced a bug](https://github.com/Paperspace/gradient-cli/pull/384#discussion_r846314866) that prevents datasets from being uploaded that contain files that are multiples of 500Mb. This became more of an issue with #389 which changes the chunk sizes to 15Mb, meaning that any file that is a multiple of 15Mb (75Mb in my case) will cause the dataset to fail to upload.
What I believe is happening is that because we faulty logic instructs us to read an additional block of data from the filesystem that doesn't exist. How this appears in my experience is that the CLI hangs indefinitely, or in a Workflow it crashes.

Replace faulty chunk counting logic

---

setup.py

Update PyYAML version to 5.3.1 to avoid running into the following error when installing with python > 3.11.
There is a PyYAML bug in 5.4 versions which caused the issue. See https://github.com/yaml/pyyaml/issues/724 for details.
```
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [54 lines of output]
running egg_info
writing lib3/PyYAML.egg-info/PKG-INFO
writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
writing top-level names to lib3/PyYAML.egg-info/top_level.txt
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module> …
```

update PyYAML version to 5.3.1
