Paperspace/gradient-cli

README.md
https://docs.paperspace.com/gradient/instances/instance-types
=> PS-7049 Update to reflect currently supported machine types

gradient/api_sdk/clients/experiment_client.py, gradient/api_sdk/models/experiment.py, gradient/api_sdk/serializers/experiment.py, gradient/cli/experiments.py, tests/functional/test_experiments.py
also, renaming username parameter
=> support for custom registry url

CODEOWNERS, releasenotes.md, source/conf.py
It would be good to make a nice release notes
=> added simple release notes

gradient/api_sdk/clients/model_client.py, gradient/api_sdk/constants.py, gradient/api_sdk/repositories/common.py, gradient/api_sdk/repositories/models.py
**Jira ticket:** https://paperspace.atlassian.net/browse/PS-12546
**Description:**
@mkutsovsky found issue with upload custom model type. Changes required to update value passed with request about custom model type. Also there were changes with renaming `file_handle` to `path`
=> Fix custom model type upload

gradient/api_sdk/clients/base_client.py, gradient/api_sdk/clients/deployment_client.py, gradient/api_sdk/clients/experiment_client.py, gradient/api_sdk/repositories/clusters.py, gradient/api_sdk/serializers/cluster.py, tests/example_responses.py, tests/functional/test_deployments.py, tests/functional/test_experiments.py
**Ticket:** https://paperspace.atlassian.net/browse/PS-12337
**Description:** We want to have message in console if we forget to pass `--vpc` flag for vpc cluster when we provide `--clusterId`
=> Add logic to validate if passed cluster_id need and vpc flag

gradient/api_sdk/clients/experiment_client.py, gradient/api_sdk/sdk_exceptions.py, gradient/api_sdk/validation_messages.py, tests/functional/test_experiments.py
**Ticket:** https://paperspace.atlassian.net/browse/PS-12939
**Description:** Add logic to validate passed modelPath without modelType to create experiment and tests for this.
=> Add logic to validate passed modelPath without modelType to create experiment.

gradient/api_sdk/repositories/clusters.py
To prevent circle ci fail on clusters list tests
=> Update logic for generating clusters list params

gradient/api_sdk/clients/base_client.py, gradient/api_sdk/clients/clusters.py, gradient/api_sdk/clients/http_client.py, gradient/api_sdk/clients/job_client.py, gradient/api_sdk/clients/machine_types_client.py, gradient/api_sdk/clients/machines_client.py, gradient/api_sdk/config.py, gradient/api_sdk/models/notebook.py, gradient/api_sdk/repositories/clusters.py, gradient/api_sdk/repositories/experiments.py, gradient/api_sdk/repositories/jobs.py, gradient/api_sdk/repositories/machine_types.py, gradient/api_sdk/repositories/machines.py, gradient/api_sdk/repositories/notebooks.py, gradient/api_sdk/repositories/projects.py, gradient/api_sdk/repositories/tensorboards.py, gradient/api_sdk/serializers/artifact.py, gradient/api_sdk/serializers/cluster.py, gradient/api_sdk/serializers/deployment.py, gradient/api_sdk/serializers/job.py, gradient/api_sdk/serializers/log.py, gradient/api_sdk/serializers/tag.py, gradient/api_sdk/serializers/utils.py, gradient/api_sdk/utils.py, gradient/api_sdk/workspace.py, gradient/cliutils.py, gradient/config.py, tests/unit/test_utils.py, tests/unit/test_workspace.py
moved as much of cli components out of sdk
changed absolute imports to relative
=> sdk and cli separation

releasenotes.md
These commands were also included in the 0.8.0a0 release
=> docs: notebooks command release notes

gradient/api_sdk/repositories/models.py, gradient/api_sdk/s3_uploader.py, tests/functional/test_uploaders.py
Waiting for changes in the operator
=> Allow upload model directory

gradient/cli/jobs.py
Made downloadDir required for job artifact download.
=> Make downloadDir required for job download artifact

gradient/api_sdk/clients/job_client.py, gradient/api_sdk/models/__init__.py, gradient/api_sdk/models/pagination.py, gradient/api_sdk/repositories/jobs.py, gradient/api_sdk/s3_downloader.py, gradient/api_sdk/serializers/utils.py, gradient/commands/jobs.py, tests/example_responses.py, tests/functional/test_jobs.py
Pagination is needed for artifacts for that have greater than a 1000. This affects listing artifacts and downloading artifacts
=> Add support for listJobArtifactsV2 endpoint to support pagination PS-15028

gradient/api_sdk/clients/__init__.py, gradient/api_sdk/clients/sdk_client.py, gradient/api_sdk/clients/workflow_client.py, gradient/api_sdk/models/__init__.py, gradient/api_sdk/models/workflows.py, gradient/api_sdk/repositories/__init__.py, gradient/api_sdk/repositories/workflows.py, gradient/api_sdk/serializers/__init__.py, gradient/api_sdk/serializers/workflows.py, gradient/cli/__init__.py, gradient/cli/workflows.py, gradient/commands/workflows.py
`gradient workflows create --projectId <project id> --name <name>`
`gradient workflows run --id <workflow id> --clusterId <cluster id> --path ./workflow.yaml --inputPath ./inputs.yaml`
workflow.yaml
```yaml
defaults:
env:
HELLO: secret:hello
resources:
instance-type: c5.xlarge
inputs:
data:
type: dataset
echo:
type: string
jobs:
job-1:
inputs:
data: workflow.inputs.data
echo: workflow.inputs.echo
outputs:
data2:
type: dataset
with:
id: test-two
echo2:
type: string
env:
FOOBAR: test
uses: container@v1
with:
args:
- bash
- -c
- find /inputs/data > /outputs/data2/list.txt; echo ENV $HELLO $FOOBAR > /outputs/echo2
image: bash:5
job-2:
inputs:
data2: job-1.outputs.data2
echo2: job-1.outputs.echo2
outputs:
data3:
type: dataset
with:
id: test-three
needs:
- job-1
uses: container@v1
with:
args:
- …
```
=> feat: add workflows PC-398

gradient/commands/common.py, gradient/commands/datasets.py, gradient/commands/deployments.py, gradient/commands/experiments.py, gradient/commands/jobs.py, gradient/commands/machines.py, gradient/commands/projects.py, tests/functional/test_deployments.py
=> fix: add namespace to urls

gradient/cli/workflows.py
goes with: https://github.com/Paperspace/PS_API/pull/3012/
=> feat(workflows): remove clusterId requirement pla-337

Pipfile, Pipfile.lock, setup.py
as requested by https://github.com/Paperspace/gradient-cli/issues/368
=> chore(dep): bump click to version 8

Pipfile.lock, gradient/api_sdk/repositories/gradient_deployments.py, gradient/cli/__init__.py, gradient/cli/cli.py, gradient/cli/gradient_deployments.py, tests/functional/test_deployments.py, tests/functional/test_tags.py, tests/unit/test_deployment_autoscaling_option_validator.py, tox.ini
This mock out api_sdk.repositories.gradient_deployments instead of pure Graphql responses.
=> chore(tests): add integration tests for deployments command

gradient/api_sdk/repositories/__init__.py, gradient/api_sdk/repositories/models.py
This inmplements a function in the Gradient Python package to access
current and historic deployments of one or more models. A user can
optionally filter on the basis of:
- Model name;
- Model project; and
- Deployment cluster
and can specify the max number of models (generally if no model name is
specified) and number of recent deployments of each model to return in
the result set.
By way of example:
```
>>> import json
>>> from gradient import models
>>>
>>>
>>> deployed_models = models.get_model_usage(
...     model_name='some-model',
...     projectId='asdf1234',
...     clusterId='4321fdsa',
...     num_models=10,
...     num_deployments=100,
...     api_key=os.getenv('PS_API_KEY')
... )
>>> print(
...     json.dumps(deployed_models, indent=4)
>>> )
[
{
"id": 1,
"name": …
```
=> feat(models): add method to show model usage

gradient/commands/datasets.py
This adds some basic retry logic for multipart upload parts so we don't
choke immediately if a single part fails for any reason. It also adds
some decidedly jank logging to update the end user on the progress of
large uploads. Unfortunately this can create some really noisy console
logs, but the way we have Halo implemented makes it just annoying enough
to do a cleaner job of things as to not be worthwhile. The important
thing is that users should now get relevant, timely information as to
how large uploads are progressing, or an informative error message if
the upload fails to complete for any reason.
=> chore(datasets): improve logging and retry logic for MPUs

README.md, gradient/__init__.py, gradient/main.py, gradient/version_checker.py, setup.py
- **chore: deprecate this package**
- **use json api**
=> chore: deprecate this package
